### ISSUE TITLE
Build fails at jack

### ISSUE THREAD

**Issue by ThePlexus** [Rudd-O/copperheados-build#1]
[  1% 897/80239] Ensuring Jack server is installed and started
FAILED: setup-jack-server 
/bin/bash -c "(prebuilts/sdk/tools/jack-admin install-server prebuilts/sdk/tools/jack-launcher.jar prebuilts/sdk/tools/jack-server-4.11.ALPHA.jar  2>&1 || (exit 0) ) && (JACK_SERVER_VM_ARGUMENTS=\"-Dfile.encoding=UTF-8 -XX:+TieredCompilation\" prebuilts/sdk/tools/jack-admin start-server 2>&1 || exit 0 ) && (prebuilts/sdk/tools/jack-admin update server prebuilts/sdk/tools/jack-server-4.11.ALPHA.jar 4.11.ALPHA 2>&1 || exit 0 ) && (prebuilts/sdk/tools/jack-admin update jack prebuilts/sdk/tools/jacks/jack-4.31.CANDIDATE.jar 4.31.CANDIDATE || exit 47 )"
Writing client settings in /root/.jack-settings
prebuilts/sdk/tools/jack-admin: line 57: /root/.jack-settings.23855: Permission denied
ln: failed to access '/root/.jack-settings': Permission denied
rm: cannot remove '/root/.jack-settings.23855': Permission denied
prebuilts/sdk/tools/jack-admin: line 68: /root/.jack-settings: Permission denied
Installing jack server in "/root/.jack-server"
mkdir: cannot create directory '/root': Permission denied
cp: failed to access '/root/.jack-server/launcher.jar': Permission denied
cp: failed to access '/root/.jack-server/server-1.jar': Permission denied
mkdir: cannot create directory '/root/.jack-server/logs': Permission denied
prebuilts/sdk/tools/jack-admin: line 278: SERVER_HOST: unbound variable
Writing client settings in /root/.jack-settings
prebuilts/sdk/tools/jack-admin: line 57: /root/.jack-settings.23871: Permission denied
ln: failed to access '/root/.jack-settings': Permission denied
rm: cannot remove '/root/.jack-settings.23871': Permission denied
prebuilts/sdk/tools/jack-admin: line 68: /root/.jack-settings: Permission denied
Jack server installation not found
Writing client settings in /root/.jack-settings
prebuilts/sdk/tools/jack-admin: line 57: /root/.jack-settings.23878: Permission denied
ln: failed to access '/root/.jack-settings': Permission denied
rm: cannot remove '/root/.jack-settings.23878': Permission denied
prebuilts/sdk/tools/jack-admin: line 68: /root/.jack-settings: Permission denied
prebuilts/sdk/tools/jack-admin: line 358: SERVER_HOST: unbound variable
Communication error with Jack server 1. Try 'jack-diagnose'
Writing client settings in /root/.jack-settings
prebuilts/sdk/tools/jack-admin: line 57: /root/.jack-settings.23889: Permission denied
ln: failed to access '/root/.jack-settings': Permission denied
rm: cannot remove '/root/.jack-settings.23889': Permission denied
prebuilts/sdk/tools/jack-admin: line 68: /root/.jack-settings: Permission denied
prebuilts/sdk/tools/jack-admin: line 358: SERVER_HOST: unbound variable
Communication error with Jack server 1. Try 'jack-diagnose'
[  1% 898/80239] build out/target/common/obj/all-event-log-tags.txt
[  1% 899/80239] host StaticLib: libaapt (out/host/linux-x86/obj/STATIC_LIBRARIES/libaapt_intermediates/libaapt.a)
[  1% 900/80239] host Java: bouncycastle-host (out/host/common/obj/JAVA_LIBRARIES/bouncycastle-host_intermediates/classes)
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
[  1% 901/80239] build out/target/product/marlin/obj/kernel/google/marlin/usr
make: Entering directory `/tmp/android-build-root/src/kernel/google/marlin'
make[1]: Entering directory `/tmp/android-build-root/src/out/target/product/marlin/obj/kernel/google/marlin'
  GEN     ./Makefile
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
drivers/soc/qcom/Kconfig:381:warning: choice value used outside its choice group
drivers/soc/qcom/Kconfig:386:warning: choice value used outside its choice group
#
# configuration written to .config
#
make[1]: Leaving directory `/tmp/android-build-root/src/out/target/product/marlin/obj/kernel/google/marlin'
make: Leaving directory `/tmp/android-build-root/src/kernel/google/marlin'
make: Entering directory `/tmp/android-build-root/src/kernel/google/marlin'
make[1]: Entering directory `/tmp/android-build-root/src/out/target/product/marlin/obj/kernel/google/marlin'
  CHK     include/generated/uapi/linux/version.h
  UPD     include/generated/uapi/linux/version.h
  WRAP    arch/arm64/include/generated/asm/bugs.h
  WRAP    arch/arm64/include/generated/asm/checksum.h
  WRAP    arch/arm64/include/generated/asm/clkdev.h
  WRAP    arch/arm64/include/generated/asm/current.h
  WRAP    arch/arm64/include/generated/asm/cputime.h
  WRAP    arch/arm64/include/generated/asm/delay.h
  WRAP    arch/arm64/include/generated/asm/dma.h
  WRAP    arch/arm64/include/generated/asm/div64.h
  WRAP    arch/arm64/include/generated/asm/dma-contiguous.h
  WRAP    arch/arm64/include/generated/asm/early_ioremap.h
  WRAP    arch/arm64/include/generated/asm/emergency-restart.h
  WRAP    arch/arm64/include/generated/asm/errno.h
  WRAP    arch/arm64/include/generated/asm/ftrace.h
  WRAP    arch/arm64/include/generated/asm/hash.h
  WRAP    arch/arm64/include/generated/asm/ioctl.h
  WRAP    arch/arm64/include/generated/asm/hw_irq.h
  WRAP    arch/arm64/include/generated/asm/ioctls.h
  WRAP    arch/arm64/include/generated/asm/ipcbuf.h
  WRAP    arch/arm64/include/generated/asm/irq_regs.h
  WRAP    arch/arm64/include/generated/asm/kdebug.h
  WRAP    arch/arm64/include/generated/asm/kmap_types.h
  WRAP    arch/arm64/include/generated/asm/local.h
  WRAP    arch/arm64/include/generated/asm/kvm_para.h
  WRAP    arch/arm64/include/generated/asm/local64.h
  WRAP    arch/arm64/include/generated/asm/mcs_spinlock.h
  WRAP    arch/arm64/include/generated/asm/mman.h
  WRAP    arch/arm64/include/generated/asm/msgbuf.h
  WRAP    arch/arm64/include/generated/asm/msi.h
  WRAP    arch/arm64/include/generated/asm/mutex.h
  WRAP    arch/arm64/include/generated/asm/pci.h
  WRAP    arch/arm64/include/generated/asm/pci-bridge.h
  WRAP    arch/arm64/include/generated/asm/poll.h
  WRAP    arch/arm64/include/generated/asm/preempt.h
  WRAP    arch/arm64/include/generated/asm/resource.h
  WRAP    arch/arm64/include/generated/asm/rwsem.h
  WRAP    arch/arm64/include/generated/asm/scatterlist.h
  WRAP    arch/arm64/include/generated/asm/sections.h
  WRAP    arch/arm64/include/generated/asm/segment.h
  WRAP    arch/arm64/include/generated/asm/sembuf.h
  WRAP    arch/arm64/include/generated/asm/serial.h
  WRAP    arch/arm64/include/generated/asm/shmbuf.h
  WRAP    arch/arm64/include/generated/asm/simd.h
  WRAP    arch/arm64/include/generated/asm/sizes.h
  WRAP    arch/arm64/include/generated/asm/sockios.h
  WRAP    arch/arm64/include/generated/asm/socket.h
  WRAP    arch/arm64/include/generated/asm/swab.h
  WRAP    arch/arm64/include/generated/asm/switch_to.h
  WRAP    arch/arm64/include/generated/asm/termbits.h
  WRAP    arch/arm64/include/generated/asm/topology.h
  WRAP    arch/arm64/include/generated/asm/termios.h
  WRAP    arch/arm64/include/generated/asm/trace_clock.h
  WRAP    arch/arm64/include/generated/asm/unaligned.h
  WRAP    arch/arm64/include/generated/asm/types.h
  WRAP    arch/arm64/include/generated/asm/user.h
  WRAP    arch/arm64/include/generated/asm/vga.h
  WRAP    arch/arm64/include/generated/asm/xor.h
  WRAP    arch/arm64/include/generated/uapi/asm/kvm_para.h
  HOSTCC  scripts/unifdef
  INSTALL usr/include/drm/ (18 files)
  INSTALL usr/include/asm-generic/ (35 files)
  INSTALL usr/include/linux/../../../usr/include/linux/staging/android/uapi/ (2 files)
  INSTALL usr/include/media/ (21 files)
  INSTALL usr/include/linux/byteorder/ (2 files)
  INSTALL usr/include/linux/caif/ (2 files)
  INSTALL usr/include/linux/can/ (5 files)
  INSTALL usr/include/linux/dvb/ (8 files)
  INSTALL usr/include/misc/ (1 file)
  INSTALL usr/include/linux/hdlc/ (1 file)
  INSTALL usr/include/mtd/ (5 files)
  INSTALL usr/include/linux/hsi/ (1 file)
  INSTALL usr/include/linux/isdn/ (1 file)
  INSTALL usr/include/rdma/ (6 files)
  INSTALL usr/include/linux/mfd/wcd9xxx/ (2 files)
  INSTALL usr/include/scsi/fc/ (4 files)
  INSTALL usr/include/linux/mfd/ (1 file)
  INSTALL usr/include/scsi/ufs/ (2 files)
  INSTALL usr/include/linux/mmc/ (3 files)
  INSTALL usr/include/scsi/ (5 files)
  INSTALL usr/include/linux/netfilter/ipset/ (4 files)
  INSTALL usr/include/sound/ (20 files)
  INSTALL usr/include/linux/netfilter/ (85 files)
  INSTALL usr/include/video/ (5 files)
  INSTALL usr/include/linux/netfilter_arp/ (2 files)
  INSTALL usr/include/linux/netfilter_bridge/ (17 files)
  INSTALL usr/include/linux/netfilter_ipv4/ (10 files)
  INSTALL usr/include/linux/netfilter_ipv6/ (12 files)
  INSTALL usr/include/linux/nfsd/ (5 files)
  INSTALL usr/include/linux/raid/ (2 files)
  INSTALL usr/include/linux/spi/ (1 file)
  INSTALL usr/include/linux/sunrpc/ (1 file)
  INSTALL usr/include/linux/tc_act/ (8 files)
  INSTALL usr/include/linux/tc_ematch/ (4 files)
  INSTALL usr/include/linux/usb/ (11 files)
  INSTALL usr/include/linux/wimax/ (1 file)
  INSTALL usr/include/linux/ (470 files)
  INSTALL usr/include/xen/ (4 files)
  INSTALL usr/include/uapi/ (0 file)
  INSTALL usr/include/asm/ (35 files)
make[1]: Leaving directory `/tmp/android-build-root/src/out/target/product/marlin/obj/kernel/google/marlin'
make: Leaving directory `/tmp/android-build-root/src/kernel/google/marlin'
ninja: build stopped: subcommand failed.
21:54:12 ninja failed with: exit status 1
make: *** [run_soong_ui] Error 1
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 2
Finished: FAILURE

**Comment by ThePlexus** [comment]
Build agent is running as user "jenkins". If i su to jenkins and run the jack script manually in the workspace, it works OK. So I guess this is a permission issue with a chroot or mount?

**Comment by shamen123** [comment]
Seems to resolve it

# diff bind-mount-dirs-android bind-mount-dirs-android.orig 
11d10
< HOME=/var/lib/jenkins
17c16
<       user=jenkins
---
>       user=$1

**Comment by ThePlexus** [comment]
replaced user=$1 with user=jenkins in bind-mount-dirs-android and that seems to do the trick

**Comment by Rudd-O** [comment]
I'm baffled that there was no error message.  What's your $USER variable during the build?

**Comment by ThePlexus** [comment]
jenkins is the user during the build.. but bind-mount-dirs-android sudo seems to set it to root if using user=$1. Im a bit baffled myself. set user=jenkins in the below and it works fine
eg;
sudo -E -- unshare -m -- bash -c '
      set -ex
      builddir=$0
      user=jenkins
