### ISSUE TITLE
local-init fsanitize unsupported?

### ISSUE THREAD

**Issue by ThePlexus** [Rudd-O/copperheados-build#2]
Getting a lot of these one the build. Is this expected? local-init is part of the copperhead mods so a little concerning to see (thousands) of these errors

error: unsupported argument 'local-init' to option 'fsanitize='

expected?

**Comment by Rudd-O** [comment]
I would not know.  Since this is a verbatim copy of the CopperheadOS build process, I recommend reporting upstream at https://github.com/copperhead/bugtracker .  Sorry.

**Comment by ThePlexus** [comment]
others see this too after checking on reddit..

https://www.reddit.com/r/CopperheadOS/comments/78nk3w/pixel_xl_build_lots_of_error_unsupported_argument/

Hypothesis: seems to only be on header-abi-dumper, so to my knowledge this is likely the fact that local-init does not exist in the stock source as a fsanitize option. Maybe. Hopefully
