### ISSUE TITLE
Setting up slave on Jenkins ver. 2.89.2, and generating keys

### ISSUE THREAD

**Issue by captainhook** [Rudd-O/copperheados-build#5]
This repo does not seem to identify the version of Jenkins used. I am using 2.89.2 and have run into an issue in creating the slave. 
![Adding node to Jenkins](https://i.imgur.com/H4AXPmh.png)

What would the launch command be? 

On a second note, what is the suggested method for generating the keys? I have copied them over from a second VM I was using for manual building.

**Comment by captainhook** [comment]
@Rudd-O please close/delete, irrelevant to this repo. Thanks

**Comment by Rudd-O** [comment]
Please close this ticket.

On January 8, 2018 10:33:05 PM GMT+01:00, captainhook <notifications@github.com> wrote:
>This repo does not seem to identify the version of Jenkins used. I am
>using 2.89.2 and have run into an issue in creating the slave. 
>![Adding node to Jenkins](https://i.imgur.com/H4AXPmh.png)
>
>What would the launch command be? 
>
>On a second note, what is the suggested method for generating the keys?
>I have copied them over from a second VM.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Rudd-O/copperheados-build/issues/5

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
